### ISSUE TITLE
💯 !!!Code Review!!! 💯

### ISSUE THREAD

**Issue by timestep** [emilyhfdong/todoApp#1]
Hello Emily!~

Me and Pat from @northone did a quick code-review for you. We did a quick overview of your code and found some suggestions 🗒️! Remember these are our opinions, take what you want and leave what you don't. I can clarify more in the comments and please don't hesitate to ask questions! We aren't perfect here, and definitely might have said something confusing 😃

Overall, it's pretty good stuff! I like how you are being very conscious of what belongs where and naming things correctly. I also like the way some of the components have been broken down!

I noticed that we have wrapped the entire app in a container. We should only wrap a component when we wish for that specific component to speak with redux or our global state.

Otherwise its generally good practice to keep our components as `presentational`, without context of where redux is.
https://github.com/emilyhfdong/todoApp/blob/bee259a7ba4ae1ce5a230d817eaf7880c6c2a80b/src/App.js#L20

I would also encourage the use of `const`. I noticed some places https://github.com/emilyhfdong/todoApp/blob/bee259a7ba4ae1ce5a230d817eaf7880c6c2a80b/src/components/homePage/HomePage.js#L17, where we are not using a const. 

On this line, we can also compose the function to be much simpler, and functional 
https://github.com/emilyhfdong/todoApp/blob/bee259a7ba4ae1ce5a230d817eaf7880c6c2a80b/src/components/homePage/HomePage.js#L16
```
const getDate = () =>  Date().split(" ").splice(4).join(" ")
```
I would encourage thinking of composing functions together to create a readable line. 🤔 We can easily infer here that to get the date, the date object is being split by the delimiter `" "` and spliced by 4 and the joined by the delimiter `" " `

https://github.com/emilyhfdong/todoApp/blob/bee259a7ba4ae1ce5a230d817eaf7880c6c2a80b/src/components/homePage/HomePage.js#L24
Good Job on keeping the render method clean! 👍 It was a good choice to make the function outside the render() block! This way we keep the render() function solely responsible for rendering the UI and its easier for other developers to understand! 😃
 
I would also suggest to think of using prefixes like `is` or `has` to denote if something is a boolean or not. https://github.com/emilyhfdong/todoApp/blob/bee259a7ba4ae1ce5a230d817eaf7880c6c2a80b/src/components/homePage/SideBar.js#L22
Here I would suggest something along the lines of `isCreateMode`. 

`showCreate` or `hideCreate` is also more valuable, since we are dealing with determining if something is available for the user to see or not. I would also lean more towards using `showCreate` rather than the negative, since the human mind has an easier time to grasp positives rather than double negatives.

I also like how you've kept components fairly lean 😃. It helps me understand what each component is doing and we can visualize what the page kind of looks like.

https://github.com/emilyhfdong/todoApp/blob/bee259a7ba4ae1ce5a230d817eaf7880c6c2a80b/src/components/homePage/SideBar.js#L73
I would still create a mapDispatchToProps here though, for readability.
```
const mapStateToProps ={ createCategory, changeCategory, deleteCategory }
```

The `TodoItem.js` feels a little heavy. https://github.com/emilyhfdong/todoApp/blob/bee259a7ba4ae1ce5a230d817eaf7880c6c2a80b/src/components/homePage/TodoItem.js

I was also confused by the similar naming structure here: https://github.com/emilyhfdong/todoApp/blob/bee259a7ba4ae1ce5a230d817eaf7880c6c2a80b/src/components/homePage/TodoItem.js#L25-L28

I was not able to understand which function name described saving to redux and which was for internal state, and what each of those functions did.

And that's all I got for now! There are a few things with mixing of internal state and redux state that was a little concerning, however I'm more curious about why you decided to build it the way you did.

Cheers! 👋

**Comment by emilyhfdong** [comment]
Hi Kevin,

Thanks for all the tips and suggestions! I will definitely keep them in mind in the future. 

😀😀
